day1: FORCE
	python3 day1/main.py
day2: FORCE
	python3 day2/main.py
day3: FORCE
	python3 day3/main.py
day4: FORCE
	python3 day4/main.py
day5: FORCE
	python3 day5/main.py
day6: FORCE
	python3 day6/main.py
day7: FORCE
	python3 day7/main.py
day8: FORCE
	python3 day8/main.py
day9: FORCE
	python3 day9/main.py
day10: FORCE
	python3 day10/main.py
day11: FORCE
	python3 day11/main.py
day12: FORCE
	python3 day12/main.py

FORCE: ;
